[package]
name = "mini-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
mini-redis = "0.4"
tokio = { version = "1", features = ["full"] }
bytes = "1"
tokio-stream = "0.1"


[[example]]
name = "hello-redis"
path = "example/hello-redis.rs"
